from __future__ import annotations

from collections.abc import Callable
from datetime import datetime
from typing import Any, Protocol


class CacheServicePort(Protocol):
    def get(self, key: str) -> Any | None: ...
    def set(self, key: str, value: Any, ttl: int = 300) -> bool: ...
    def delete_prefix(self, prefix: str) -> int: ...


class KlineStorePort(Protocol):
    def get_before(self, symbol: str, timeframe: str, end_ts: int, limit: int) -> list[list[float]]: ...
    def get_after(self, symbol: str, timeframe: str, start_ts: int, limit: int) -> list[list[float]]: ...
    def get_range(self, symbol: str, timeframe: str, start_ts: int, end_ts: int) -> list[list[float]]: ...
    def get_latest(self, symbol: str, timeframe: str, limit: int) -> list[list[float]]: ...
    def save(self, symbol: str, timeframe: str, rows: list[list[float]]) -> None: ...


class IndicatorRepositoryPort(Protocol):
    def list_active_meta(self, category: str | None = None) -> list[dict[str, Any]]: ...
    def get_history_points(
        self,
        indicator_ids: list[str],
        *,
        start_date: datetime | None = None,
    ) -> dict[str, list[dict[str, Any]]]: ...
    def upsert_points(self, data_points: list[dict[str, Any]], meta_catalog: dict[str, tuple[str, str, str]]) -> None: ...


class FactorResearchRepositoryPort(Protocol):
    def get_dataset_by_signature(self, signature: str) -> dict[str, Any] | None: ...
    def get_dataset_rows(self, dataset_id: int) -> list[dict[str, Any]]: ...
    def create_dataset(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_research_run(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_research_runs(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def get_research_run(self, run_id: int) -> dict[str, Any] | None: ...


class FundingRateStorePort(Protocol):
    def save_many(self, rows: list[dict[str, Any]]) -> int: ...
    def list_history(
        self,
        *,
        exchange: str,
        market_type: str,
        symbol: str | None = None,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
        limit: int | None = None,
    ) -> list[dict[str, Any]]: ...
    def latest(self, *, exchange: str, market_type: str, symbol: str) -> dict[str, Any] | None: ...
    def count(self, *, exchange: str, market_type: str, symbol: str) -> int: ...


class BinanceMarketResearchStorePort(Protocol):
    def save_items(self, **kwargs: Any) -> int: ...
    def list_items(self, **kwargs: Any) -> list[dict[str, Any]]: ...


class SentimentRepositoryPort(Protocol):
    def get_latest_date(self) -> datetime | None: ...
    def save_missing(self, records: list[dict[str, Any]]) -> int: ...
    def list_history(self, start_date: datetime | None, end_date: datetime | None) -> dict[str, int]: ...
    def get_latest_index(self) -> dict[str, int | str] | None: ...


DataRetentionCleanup = Callable[[], Any]
