// This file is generated from backend FastAPI route contracts.
// Do not edit manually.

type RouteParams = Record<string, string | number>
export type ApiQueryMeta = { aliases?: Record<string, string>; repeatedKeys?: readonly string[] }

const fillRoute = (template: string, params: RouteParams = {}) => template.replace(/\{([^}]+)\}/g, (_, key: string) => {
  const value = params[key]
  if (value === undefined || value === null || value === '') throw new Error(`Missing API route param: ${key}`)
  return encodeURIComponent(String(value))
})

const routeTemplates = {
  analyze_factors: "/factor-research/analyze",
  compare_pairs: "/tools/compare_pairs",
  create_indicator: "/backtest/indicators",
  create_strategy_template: "/backtest/templates",
  create_strategy_version: "/backtest/strategies",
  dca_simulate: "/tools/dca_simulate",
  delete_backtest: "/backtest/{backtest_id}",
  delete_paper_run: "/paper/{run_id}",
  get_api_status: "/status",
  get_backtest: "/backtest/{backtest_id}",
  get_binance_market_breakout_monitor: "/binance/market/breakout_monitor",
  get_binance_market_page: "/binance/market/page",
  get_binance_rwa_asset_market_status: "/binance/rwa/asset_market_status",
  get_binance_rwa_dynamic: "/binance/rwa/dynamic",
  get_binance_rwa_kline: "/binance/rwa/kline",
  get_binance_rwa_market_status: "/binance/rwa/market_status",
  get_binance_rwa_meta: "/binance/rwa/meta",
  get_binance_rwa_symbols: "/binance/rwa/symbols",
  get_binance_spot_agg_trades: "/binance/spot/agg_trades",
  get_binance_spot_book_ticker: "/binance/spot/book_ticker",
  get_binance_spot_depth: "/binance/spot/depth",
  get_binance_spot_exchange_info: "/binance/spot/exchange_info",
  get_binance_spot_klines: "/binance/spot/klines",
  get_binance_spot_price: "/binance/spot/price",
  get_binance_spot_ticker_24hr: "/binance/spot/ticker_24hr",
  get_binance_spot_ticker_window: "/binance/spot/ticker_window",
  get_binance_spot_trades: "/binance/spot/trades",
  get_binance_spot_ui_klines: "/binance/spot/ui_klines",
  get_binance_usdm_basis: "/binance/futures/usdm/basis",
  get_binance_usdm_exchange_info: "/binance/futures/usdm/exchange_info",
  get_binance_usdm_funding_history: "/binance/futures/usdm/funding_history",
  get_binance_usdm_funding_info: "/binance/futures/usdm/funding_info",
  get_binance_usdm_long_short_ratio: "/binance/futures/usdm/long_short_ratio",
  get_binance_usdm_mark_price: "/binance/futures/usdm/mark_price",
  get_binance_usdm_open_interest: "/binance/futures/usdm/open_interest",
  get_binance_usdm_open_interest_stats: "/binance/futures/usdm/open_interest_stats",
  get_binance_usdm_taker_volume: "/binance/futures/usdm/taker_volume",
  get_binance_usdm_ticker_24hr: "/binance/futures/usdm/ticker_24hr",
  get_binance_usdm_top_trader_accounts: "/binance/futures/usdm/top_trader_accounts",
  get_binance_usdm_top_trader_positions: "/binance/futures/usdm/top_trader_positions",
  get_binance_web3_address_pnl_rank: "/binance/web3/address_pnl_rank",
  get_binance_web3_heat_rank: "/binance/web3/heat_rank",
  get_binance_web3_meme_rank: "/binance/web3/meme_rank",
  get_binance_web3_smart_money_inflow: "/binance/web3/smart_money_inflow",
  get_binance_web3_social_hype: "/binance/web3/social_hype",
  get_binance_web3_token_audit: "/binance/web3/token_audit",
  get_binance_web3_token_dynamic: "/binance/web3/token_dynamic",
  get_binance_web3_token_kline: "/binance/web3/token_kline",
  get_binance_web3_unified_token_rank: "/binance/web3/unified_token_rank",
  get_config: "/config",
  get_crypto_index: "/crypto_index",
  get_currencies: "/currencies",
  get_current_funding_rate: "/funding-rate/current",
  get_current_price: "/price/current",
  get_current_price_batch: "/price/current/batch",
  get_factor_catalog: "/factor-research/catalog",
  get_factor_run: "/factor-research/runs/{run_id}",
  get_funding_rate_history: "/funding-rate/history",
  get_index_history: "/indexes/history",
  get_index_pricing_history: "/indexes/pricing/history",
  get_kline_tail: "/klines/tail",
  get_latest_index: "/indexes/latest",
  get_latest_index_pricing: "/indexes/pricing/latest",
  get_latest_klines: "/klines/latest",
  get_llm_config: "/llm-config",
  get_market_full_history: "/full_history",
  get_market_full_history_batch: "/full_history/batch",
  get_market_history: "/history",
  get_market_indicators: "/indicators",
  get_paper_run: "/paper/{run_id}",
  get_realtime_analysis: "/realtime",
  get_strategy_editor_contract: "/backtest/editor-contract",
  get_technical_metrics: "/technical-metrics",
  get_trade_setup: "/trade-setup",
  list_backtests: "/backtest/list",
  list_factor_runs: "/factor-research/runs",
  list_indicator_engines: "/backtest/indicator-engines",
  list_indicators: "/backtest/indicators",
  list_market_indexes: "/indexes",
  list_market_symbols: "/symbols",
  list_paper_runs: "/paper/list",
  list_strategies: "/backtest/strategies",
  list_strategy_templates: "/backtest/templates",
  start_backtest: "/backtest/start",
  start_factor_backtest: "/factor-research/runs/{run_id}/backtest",
  start_factor_paper_run: "/factor-research/runs/{run_id}/paper",
  start_paper_run: "/paper/start",
  stop_paper_run: "/paper/{run_id}/stop",
  sync_funding_rate_history: "/funding-rate/sync",
  update_llm_config: "/llm-config",
} as const

export type ApiRouteName = keyof typeof routeTemplates

export const apiRoute = (name: ApiRouteName, params?: RouteParams) => fillRoute(routeTemplates[name], params)

export const serializeApiQueryParams = <T extends object>(params: T, meta?: ApiQueryMeta) => {
  const query = new URLSearchParams()
  Object.entries(params as Record<string, unknown>).forEach(([key, value]) => {
    if (value === null || value === undefined || value === '') return
    const resolvedKey = meta?.aliases?.[key] ?? key
    const repeatedKeys = meta?.repeatedKeys ?? []
    if (Array.isArray(value)) {
      value.forEach((item) => {
        if (item !== null && item !== undefined && item !== '') query.append(resolvedKey, String(item))
      })
      return
    }
    if (repeatedKeys.includes(key)) {
      query.append(resolvedKey, String(value))
      return
    }
    query.set(resolvedKey, String(value))
  })
  return query.toString()
}

export const API_QUERY_META = {
  analyze_factors: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  compare_pairs: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  create_indicator: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  create_strategy_template: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  create_strategy_version: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  dca_simulate: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  delete_backtest: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  delete_paper_run: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_api_status: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_backtest: {"defaults": {"page": 1, "page_size": 100}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_market_breakout_monitor: {"defaults": {"min_rise_pct": 5.0, "limit": 18, "quote_asset": "USDT"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_market_page: {"defaults": {"min_rise_pct": 5.0, "limit": 24, "quote_asset": "USDT"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_asset_market_status: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_dynamic: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_kline: {"defaults": {"interval": "1d", "limit": 120}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_market_status: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_meta: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_rwa_symbols: {"defaults": {"platform_type": 1}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_agg_trades: {"defaults": {"limit": 50}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_book_ticker: {"defaults": {}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_depth: {"defaults": {"limit": 20}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_exchange_info: {"defaults": {}, "repeatedKeys": ["symbols", "permissions"], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_klines: {"defaults": {"limit": 200}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_price: {"defaults": {}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_ticker_24hr: {"defaults": {}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_ticker_window: {"defaults": {}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_trades: {"defaults": {"limit": 50}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_spot_ui_klines: {"defaults": {"limit": 200}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_basis: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_exchange_info: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_funding_history: {"defaults": {"limit": 100}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_funding_info: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_long_short_ratio: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_mark_price: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_open_interest: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_open_interest_stats: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_taker_volume: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_ticker_24hr: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_top_trader_accounts: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_usdm_top_trader_positions: {"defaults": {"limit": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_address_pnl_rank: {"defaults": {"period": "30d", "tag": "ALL", "page_no": 1, "page_size": 25}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_heat_rank: {"defaults": {"chain_id": "56", "size": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_meme_rank: {"defaults": {"chain_id": "56"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_smart_money_inflow: {"defaults": {"period": "24h", "tag_type": 2}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_social_hype: {"defaults": {"target_language": "zh", "time_range": 1, "sentiment": "All", "social_language": "ALL"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_token_audit: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_token_dynamic: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_binance_web3_token_kline: {"defaults": {"interval": "15min", "limit": 240, "pm": "p"}, "repeatedKeys": [], "aliases": {"from_time": "from", "to_time": "to"}} as ApiQueryMeta,
  get_binance_web3_unified_token_rank: {"defaults": {"rank_type": 10, "period": 50, "sort_by": 0, "order_asc": false, "page": 1, "size": 20}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_config: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_crypto_index: {"defaults": {"top_n": 20, "days": 90}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_currencies: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_current_funding_rate: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_current_price: {"defaults": {"timeframe": "1d"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_current_price_batch: {"defaults": {"timeframe": "1d"}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_factor_catalog: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_factor_run: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_funding_rate_history: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_index_history: {"defaults": {"timeframe": "1d", "start_date": "2010-01-01"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_index_pricing_history: {"defaults": {"timeframe": "1d", "start_date": "2010-01-01"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_kline_tail: {"defaults": {"limit": 2}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_latest_index: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_latest_index_pricing: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_latest_klines: {"defaults": {"limit": 1000}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_llm_config: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_market_full_history: {"defaults": {"timeframe": "1d", "start_date": "2010-01-01", "fetch_policy": "hydrate"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_market_full_history_batch: {"defaults": {"timeframe": "1d", "start_date": "2010-01-01", "fetch_policy": "hydrate"}, "repeatedKeys": ["symbols"], "aliases": {}} as ApiQueryMeta,
  get_market_history: {"defaults": {"limit": 500}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_market_indicators: {"defaults": {"days": 30}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_paper_run: {"defaults": {"page": 1, "page_size": 100}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_realtime_analysis: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_strategy_editor_contract: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_technical_metrics: {"defaults": {"timeframe": "1d", "limit": 120, "atr_period": 14, "volatility_period": 20}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  get_trade_setup: {"defaults": {"timeframe": "1h", "limit": 120, "account_size": 1000, "style": "Scalping", "strategy": "最大收益", "mode": "rules"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_backtests: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_factor_runs: {"defaults": {"limit": 20}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_indicator_engines: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_indicators: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_market_indexes: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_market_symbols: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_paper_runs: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_strategies: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  list_strategy_templates: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  start_backtest: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  start_factor_backtest: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  start_factor_paper_run: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  start_paper_run: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  stop_paper_run: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  sync_funding_rate_history: {"defaults": {"start_date": "2019-09-01"}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
  update_llm_config: {"defaults": {}, "repeatedKeys": [], "aliases": {}} as ApiQueryMeta,
} as const

export const API_BODY_DEFAULTS = {
  analyze_factors: {"symbol": "BTC/USDT", "timeframe": "1d", "days": 365, "horizon_bars": 3, "max_lag_bars": 7, "categories": [], "factor_ids": []},
  compare_pairs: {"symbol_a": "BTC", "symbol_b": "ETH", "days": 7, "timeframe": "1h"},
  create_indicator: {"description": null, "params": []},
  create_strategy_template: {"description": null, "indicator_keys": [], "default_parameter_space": {}},
  create_strategy_version: {"description": null, "parameter_space": {}, "notes": null, "make_default": true},
  dca_simulate: {"symbol": "BTC/USDT", "amount": 100.0, "start_date": null, "investment_time": "23:00", "timezone": "Asia/Shanghai", "days": null, "strategy": "standard", "strategy_params": {}},
  delete_backtest: {},
  delete_paper_run: {},
  get_api_status: {},
  get_backtest: {},
  get_binance_market_breakout_monitor: {},
  get_binance_market_page: {},
  get_binance_rwa_asset_market_status: {},
  get_binance_rwa_dynamic: {},
  get_binance_rwa_kline: {},
  get_binance_rwa_market_status: {},
  get_binance_rwa_meta: {},
  get_binance_rwa_symbols: {},
  get_binance_spot_agg_trades: {},
  get_binance_spot_book_ticker: {},
  get_binance_spot_depth: {},
  get_binance_spot_exchange_info: {},
  get_binance_spot_klines: {},
  get_binance_spot_price: {},
  get_binance_spot_ticker_24hr: {},
  get_binance_spot_ticker_window: {},
  get_binance_spot_trades: {},
  get_binance_spot_ui_klines: {},
  get_binance_usdm_basis: {},
  get_binance_usdm_exchange_info: {},
  get_binance_usdm_funding_history: {},
  get_binance_usdm_funding_info: {},
  get_binance_usdm_long_short_ratio: {},
  get_binance_usdm_mark_price: {},
  get_binance_usdm_open_interest: {},
  get_binance_usdm_open_interest_stats: {},
  get_binance_usdm_taker_volume: {},
  get_binance_usdm_ticker_24hr: {},
  get_binance_usdm_top_trader_accounts: {},
  get_binance_usdm_top_trader_positions: {},
  get_binance_web3_address_pnl_rank: {},
  get_binance_web3_heat_rank: {},
  get_binance_web3_meme_rank: {},
  get_binance_web3_smart_money_inflow: {},
  get_binance_web3_social_hype: {},
  get_binance_web3_token_audit: {},
  get_binance_web3_token_dynamic: {},
  get_binance_web3_token_kline: {},
  get_binance_web3_unified_token_rank: {},
  get_config: {},
  get_crypto_index: {},
  get_currencies: {},
  get_current_funding_rate: {},
  get_current_price: {},
  get_current_price_batch: {},
  get_factor_catalog: {},
  get_factor_run: {},
  get_funding_rate_history: {},
  get_index_history: {},
  get_index_pricing_history: {},
  get_kline_tail: {},
  get_latest_index: {},
  get_latest_index_pricing: {},
  get_latest_klines: {},
  get_llm_config: {},
  get_market_full_history: {},
  get_market_full_history_batch: {},
  get_market_history: {},
  get_market_indicators: {},
  get_paper_run: {},
  get_realtime_analysis: {},
  get_strategy_editor_contract: {},
  get_technical_metrics: {},
  get_trade_setup: {},
  list_backtests: {},
  list_factor_runs: {},
  list_indicator_engines: {},
  list_indicators: {},
  list_market_indexes: {},
  list_market_symbols: {},
  list_paper_runs: {},
  list_strategies: {},
  list_strategy_templates: {},
  start_backtest: {"strategy_key": "ema_rsi_macd", "strategy_version": null, "timeframe": "1h", "start_date": "2025-10-23", "end_date": "2026-04-21", "initial_cash": 100000.0, "fee_rate": 0.1, "portfolio": {"symbols": ["BTC/USDT", "ETH/USDT"], "max_open_trades": 2, "position_size_pct": 25.0, "stake_mode": "fixed"}, "research": {"slippage_bps": 5.0, "funding_rate_daily": 0.0, "in_sample_ratio": 100.0, "optimize_metric": "sharpe", "optimize_trials": 0, "rolling_windows": 0}},
  start_factor_backtest: {"initial_cash": 100000.0, "fee_rate": 0.1, "position_size_pct": 25.0, "stake_mode": "fixed", "entry_threshold": null, "exit_threshold": null, "stoploss_pct": -0.08, "takeprofit_pct": 0.16, "max_hold_bars": 20},
  start_factor_paper_run: {"initial_cash": 100000.0, "fee_rate": 0.1, "position_size_pct": 25.0, "stake_mode": "fixed", "entry_threshold": null, "exit_threshold": null, "stoploss_pct": -0.08, "takeprofit_pct": 0.16, "max_hold_bars": 20},
  start_paper_run: {"strategy_key": "ema_rsi_macd", "strategy_version": null, "timeframe": "1h", "initial_cash": 100000.0, "fee_rate": 0.1, "portfolio": {"symbols": ["BTC/USDT", "ETH/USDT"], "max_open_trades": 2, "position_size_pct": 25.0, "stake_mode": "fixed"}},
  stop_paper_run: {},
  sync_funding_rate_history: {},
  update_llm_config: {"apiKey": null, "baseUrl": "", "modelId": "", "reasoningEnabled": false},
} as const
