from __future__ import annotations

from typing import Any, Protocol

from app.contracts.backtest import (
    BacktestPreviewCommand,
    BacktestStartCommand,
    CreateIndicatorDefinitionCommand,
    CreateStrategyTemplateCommand,
    CreateStrategyVersionCommand,
    EvolveStrategyFromBacktestCommand,
    PaperStartCommand,
)
from app.contracts.factor import FactorExecutionConfig
from app.contracts.tools import ComparePairsCommand, SimulateDcaCommand


class BacktestCommandPort(Protocol):
    async def preview_backtest(self, command: BacktestPreviewCommand) -> dict[str, Any]: ...
    async def start_backtest(self, command: BacktestStartCommand) -> dict[str, Any]: ...
    async def start_paper_run(self, command: PaperStartCommand) -> dict[str, Any]: ...
    async def stop_paper_run(self, run_id: int) -> dict[str, Any]: ...
    async def delete_backtest(self, backtest_id: int) -> dict[str, Any]: ...
    async def delete_paper_run(self, run_id: int) -> dict[str, Any]: ...
    async def create_template(self, command: CreateStrategyTemplateCommand) -> dict[str, Any]: ...
    async def create_indicator(self, command: CreateIndicatorDefinitionCommand) -> dict[str, Any]: ...
    async def create_strategy_version(self, command: CreateStrategyVersionCommand) -> dict[str, Any]: ...
    async def evolve_strategy_from_backtest(self, command: EvolveStrategyFromBacktestCommand) -> dict[str, Any]: ...


class BacktestQueryPort(Protocol):
    async def list_strategies(self) -> list[dict[str, Any]]: ...
    async def list_templates(self) -> list[dict[str, Any]]: ...
    async def get_editor_contract(self) -> dict[str, Any]: ...
    async def list_indicators(self) -> list[dict[str, Any]]: ...
    async def list_indicator_engines(self) -> list[dict[str, Any]]: ...
    async def list_runs(self) -> list[dict[str, Any]]: ...
    async def get_run(self, backtest_id: int, page: int, page_size: int) -> dict[str, Any]: ...
    async def list_paper_runs(self) -> list[dict[str, Any]]: ...
    async def get_paper_run(self, run_id: int, page: int, page_size: int) -> dict[str, Any]: ...


class FactorResearchPort(Protocol):
    async def get_catalog_async(self) -> dict[str, Any]: ...
    async def analyze_async(self, **kwargs: Any) -> dict[str, Any]: ...
    async def list_runs_async(self, *, limit: int = 20) -> list[dict[str, Any]]: ...
    async def get_run_async(self, run_id: int) -> dict[str, Any]: ...


class FactorExecutionPort(Protocol):
    async def run_backtest_async(self, config: FactorExecutionConfig) -> int: ...


class FactorPaperRunPort(Protocol):
    async def start_run(self, config: FactorExecutionConfig) -> dict[str, Any]: ...


class ToolsAppPort(Protocol):
    async def simulate_dca(self, command: SimulateDcaCommand) -> dict[str, Any]: ...
    async def compare_pairs(self, command: ComparePairsCommand) -> dict[str, Any]: ...


class MarketQueryPort(Protocol):
    valid_symbols: list[str]
    valid_timeframes: list[str]

    async def get_realtime(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_realtime_ws_payload(self, **kwargs: Any) -> dict[str, Any] | None: ...
    async def get_history(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_recent_klines(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_live_kline_tail(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_current_price(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_current_price_batch(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_full_history(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_full_history_batch(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_technical_metrics(self, **kwargs: Any) -> dict[str, Any]: ...


class MarketInsightPort(Protocol):
    async def get_indicators_async(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def get_dli_liquidity_async(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_trade_setup(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_crypto_index(self, **kwargs: Any) -> dict[str, Any]: ...


class MarketWebSocketPort(Protocol):
    async def parse_params_or_reject(self, websocket: Any, valid_symbols: list[str], valid_timeframes: list[str]) -> dict[str, Any] | None: ...


class IndexDataPort(Protocol):
    async def list_indexes_async(self) -> list[Any]: ...
    async def get_history_async(self, **kwargs: Any) -> Any: ...
    async def get_latest_async(self, **kwargs: Any) -> Any: ...
    async def get_pricing_history_async(self, **kwargs: Any) -> Any: ...
    async def get_latest_pricing_async(self, **kwargs: Any) -> Any: ...


class FundingRateAppPort(Protocol):
    async def get_current_funding_rate(self, symbol: str) -> dict[str, Any]: ...
    async def sync_funding_rate_history(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_funding_rate_history(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceSpotPort(Protocol):
    async def get_exchange_info(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_ticker_24hr(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_ticker_window(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_price(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_book_ticker(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_depth(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_trades(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_agg_trades(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_klines(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceUsdmPort(Protocol):
    async def get_exchange_info(self) -> dict[str, Any]: ...
    async def get_ticker_24hr(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_mark_price(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_funding_info(self) -> dict[str, Any]: ...
    async def get_funding_history(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_open_interest(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_open_interest_stats(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_long_short_ratio(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_top_trader_accounts(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_top_trader_positions(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_taker_volume(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_basis(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_contract_research_detail(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceMarketPagePort(Protocol):
    async def get_page_payload(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceMarketPort(Protocol):
    spot: BinanceSpotPort
    usdm: BinanceUsdmPort
    page: BinanceMarketPagePort


class BinanceWeb3RanksPort(Protocol):
    async def get_social_hype_leaderboard(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_unified_token_rank(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_smart_money_inflow_rank(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_meme_rank(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_address_pnl_rank(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceWeb3HeatRanksPort(Protocol):
    async def get_web3_heat_rank(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_web3_heat_rank_boards(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceWeb3RwaPort(Protocol):
    async def list_symbols(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_meta(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_market_status(self) -> dict[str, Any]: ...
    async def get_asset_market_status(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_dynamic(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_kline(self, **kwargs: Any) -> dict[str, Any]: ...


class BinanceWeb3TokensPort(Protocol):
    async def get_dynamic(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_kline(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_audit(self, **kwargs: Any) -> dict[str, Any]: ...


class DatabaseRuntimePort(Protocol):
    engine: Any
    source: str


class CurrencyRatePort(Protocol):
    async def get_rates(self) -> dict[str, Any]: ...


class LlmConfigPort(Protocol):
    def read_config(self) -> dict[str, Any]: ...
    def save_config(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class FredApiConfigPort(Protocol):
    def read_config(self) -> dict[str, Any]: ...
    def save_config(self, payload: dict[str, Any]) -> dict[str, Any]: ...
